#!/usr/bin/env bash
#Process and PID file
touch /var/run/myscript.pid
PID_FILE="/var/run/myscript.pid"

echo "$$" > "$PID_FILE" 
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid ' SIGQUIT SIGTERM

while true; do
 echo "To infinity and beyond"
    sleep 2
done

