#!/usr/bin/env bash
# This script runs indefinitely, writing a message to a file every 2 seconds

# Start an infinite loop
while true
do
    # Append the message to the log file
    echo "I am alive!" >> /tmp/my_process
    
    # Pause for 2 seconds
    sleep 2
done
